### PR TITLE
WIP: updating, to use our fork's yaml

### PR DESCRIPTION
**Pull request by matzew**
## Proposed Changes

* updates to yaml
*
*

### CODE REVIEW

**Comment by matzew** [comment]
@aliok I think this thing is not yet ready ? 

https://github.com/openshift-knative/eventing-operator/tree/release-0.13/deploy/olm-catalog/knative-eventing-operator

it lacks 0.13 content.

also has the old `eventings.operator.knative.dev` CRD

**Comment by aliok** [comment]
@matzew I wouldn't worry about the OLM files.

1. OLM files are checked in at upstream repo only for easier creation of the files again. `operator-sdk gen csv` uses previous OLM files to generate new files.
2. We don't need the OLM files for this repository as we're not publishing our fork on OperatorHub or something. We have the OLM metadata for deployment of the upstream operator in our serverless operator.
3. I always add the OLM metadata for the upstream operator, but this time I haven't done it yet.

Other than that, I say this PR is good. Gonna try testing it now.

**Comment by aliok** [comment]
Tested using these instructions:

- Built this PR branch using `ko publish ./cmd/manager`
- That published `docker.io/aliok/manager-f1ecf4e236a455a91a2eb955def6b11b@sha256:9140d4f06ed278ca430331b7e5dae179ccef4429131e8131194f2487a7c76741` as the image
- Changed the upstream operator image in https://github.com/openshift-knative/serverless-operator/pull/126/files#diff-b466a37bd25835bf7c89df6eef60bb62R305
- Then did the instructions at https://github.com/openshift-knative/serverless-operator/pull/126

All good.
We have our own images used for Knative controllers.

**Comment by aliok** [comment]
/lgtm

Let's merge this anyway. If you think OLM stuff is necessary, I can send a separate PR for that.

**Comment by aliok** [comment]
/hold

I found something...
I saw for some reason the order of things in the file is different than the upstream file.

For example, the webhook creation fails because of that as service for the webhook needs to be created before the registration of the webhook.

How do we create the manifest file? Can't we simply take the upstream file and delete the comments and empty lines? What other changes do we need?

UPDATE: not sure if it happens always... Everything worked fine with the old manifest though. I think if we keep the files identical except the images we wouldn't have this problem.

@matzew

**Comment by matzew** [comment]
@aliok  the file is different, b/c of 
* images
* container names

we can do this:
- take the upstream file, change the container names, like you did on our 0.13 branch, and replace the grc.io images ?

**Comment by aliok** [comment]
let me take the upstream file and change images and container names @matzew

**Pull request closed without merging**
