### PR TITLE
adding deprecated label to "legacy" sources

### PR DESCRIPTION
**Pull request by matzew**
For SRVKE-420

## Proposed Changes

* adding deprecated labels to "legacy" source types

### CODE REVIEW

**Comment by invincibleJai** [comment]
@matzew thanks for updating it, with this containerSource will get deprecated as we only have `containersources.sources.eventing.knative.dev` for containerSource and not `containersources.sources.knative.dev`

**Comment by matzew** [comment]
@invincibleJai on 0.13 there is ONLY the `containersources.sources.eventing.knative.dev` - that was marked as _deprecated_ in fav. of the sinkbinding. (original idea around 0.13 release cut).

I wrote a migration guide:
* https://github.com/knative/docs/blob/master/docs/eventing/migration/sinkbinding.md

However, there was lot's of noise, disagreement and bikeshed.

With the result that in [0.14 ](https://github.com/knative/eventing/blob/v0.14.2/config/core/resources/containersource.yaml) it got added back:
* see the PR for details: https://github.com/knative/eventing/pull/2824

Note: It did "re-introduce" in `containersources.sources.knative.dev` API group

**Review by invincibleJai — COMMENTED** [review]
Thanks , looks good :)

**Pull request merged**
